version: "3"
services:
    nginx:
        image: nginx:1.13-alpine
        container_name: symfonySS.nginx
        ports:
            - 80:80
        volumes:
            - .:/usr/share/nginx/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    php:
        image: php:7.4-fpm-alpine
        container_name: symfonySS.php
        volumes:
            - .:/usr/share/nginx/html
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        environment:
            XDEBUG_CONFIG: "remote_host=192.168.100.20 remote_port=9000 idekey=PHPSTORM"
            PHP_IDE_CONFIG: "serverName=local"
    db:
        image: mysql:5.7
        container_name: symfonySS.mysql
        restart: always
        environment:
            MYSQL_DATABASE: 'db'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: 'q'
            MYSQL_ROOT_PASSWORD: 'q'
        ports:
            - '3306:3306'
        expose:
            - '3306'
        volumes:
            - "./.mysql-data/db:/var/lib/mysql"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: symfonySS.phpmyadmin
        links:
            - db
        environment:
            - PMA_HOST=mysql
            - PMA_PORT=3306
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - 81:80
    #adminer:
    #    image: adminer
    #    container_name: symfonySS.adminer
    #    restart: always
    #    ports:
    #        - 82:8080
    #    depends_on:
    #        - db
