services:
    core.route.loader:
        class: app\bundles\CoreBundle\RouteLoader\RouteLoader
        arguments:
            - ['GET', 'POST']
            - # // TODO eztenv paraméterekbe áttenni
        tags:
            - { name: routing.loader }
    app\bundles\CoreBundle\Responder\Responder:
        autowire: true
    json.deserialize.listener.request:
        class: app\bundles\CoreBundle\Listener\JsonRequestDeserializeListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
